services:
  reth:
    image: "caudenacom/reth:${BUDDY_EXECUTION_REVISION}"
    container_name: reth
    restart: unless-stopped
    ports:
      - "${RPC_ADDR}:${METRICS_PORT}:9002"
      - "${RPC_ADDR}:8545:8547"
      - "${RPC_ADDR}:8546:8548"
      - "${NODE_IP}:30304:30304"
      - "${NODE_IP}:30304:30304/udp"
      - "${NODE_IP}:9200:9200/udp"
    command: >
      node
      --chain mainnet
      --datadir=/data
      --port 30304
      --discovery.port 30304
      --authrpc.addr=0.0.0.0
      --authrpc.port=8551
      --authrpc.jwtsecret=/data/jwt.hex
      --http
      --http.api all
      --http.addr=0.0.0.0
      --http.port=8547
      --ws
      --ws.addr=0.0.0.0
      --ws.port=8548
      --rpc.max-connections=4096
      --rpc.max-response-size=1000
      --db.read-transaction-timeout=0
      --metrics=0.0.0.0:9002
      --log.file.directory=/logs
      --log.file.max-size=200
      --log.file.max-files=5
      --log.file.filter=info
    volumes:
      - /home/deploy/eth_data:/data
      - /home/deploy/eth_node/logs:/logs
    networks:
      - el-cl

networks:
  el-cl:
    name: el-cl
    driver: bridge