[package]
name = "beacon-api-sidecar-fetcher"
version = "0.1.0"
publish = false
edition.workspace = true
license.workspace = true

[dependencies]
reth.workspace = true
reth-node-ethereum.workspace = true

alloy-rpc-types-beacon.workspace = true

serde.workspace = true
serde_json.workspace = true
clap.workspace = true
futures-util.workspace = true
eyre.workspace = true
thiserror.workspace = true
reqwest.workspace = true
